name: opensearch
title: OpenSearch
icon: opensearch

services:
- name: opensearch
  title: OpenSearch
  service: opensearch
  required: true
  volumes:
  - name: data
    size: 20
  workloads:
  - name: main
    containers:
    - name: opensearch
      resources:
        request:
          cpu: 1000
          memory: 2048
        limit:
          cpu: 2000
          memory: 4096
